services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  postgres:
    image: postgres:18
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - "15432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    hostname: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5


  notifyhub-api:
    build: .
    hostname: notifyhub-api
    container_name: notifyhub-api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000

  notifyhub-worker:
    build: .
    hostname: notifyhub-worker
    container_name: notifyhub-worker
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: celery -A src.app.tasks.celery_app worker --loglevel=info


  flower:
    build: .
    hostname: flower
    container_name: flower
    restart: always
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A src.app.tasks.celery_app flower --port=5555


volumes:
  rabbitmq-data:
  pg_data: